remove __del__ it causes issues
Exception ignored in: <function SandboxShellTool.__del__ at 0x7c1218c4d120>
Traceback (most recent call last):
  File "/home/samos/workspace/crewai_example/.venv/lib/python3.12/site-packages/sandboxai/experimental/crewai.py", line 44, in __del__
  File "/home/samos/workspace/crewai_example/.venv/lib/python3.12/site-packages/sandboxai/sandbox.py", line 85, in delete
  File "/home/samos/workspace/crewai_example/.venv/lib/python3.12/site-packages/sandboxai/client/v1.py", line 122, in delete_sandbox
  File "/home/samos/workspace/crewai_example/.venv/lib/python3.12/site-packages/requests/sessions.py", line 671, in delete
  File "/home/samos/workspace/crewai_example/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
  File "/home/samos/workspace/crewai_example/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
  File "/home/samos/workspace/crewai_example/.venv/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=33205): Max retries exceeded with url: /v1/spaces/default/sandboxes/ke4vp43s96ssyjo4rqeo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c122614bfe0>: Failed to establish a new connection: [Errno 111] Connection refused'))